
package ma.fstt.ws.carburant;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CarburantServiceMethod", targetNamespace = "http://carburant.ws.fstt.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarburantService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteCarburant", targetNamespace = "http://carburant.ws.fstt.ma/", className = "ma.fstt.ws.carburant.DeleteCarburant")
    @ResponseWrapper(localName = "deleteCarburantResponse", targetNamespace = "http://carburant.ws.fstt.ma/", className = "ma.fstt.ws.carburant.DeleteCarburantResponse")
    @Action(input = "http://carburant.ws.fstt.ma/CarburantService/deleteCarburantRequest", output = "http://carburant.ws.fstt.ma/CarburantService/deleteCarburantResponse")
    public void deleteCarburant(
        @WebParam(name = "arg0", targetNamespace = "")
        Carburant arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ma.fstt.ws.carburant.Carburant
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCarburant", targetNamespace = "http://carburant.ws.fstt.ma/", className = "ma.fstt.ws.carburant.FindCarburant")
    @ResponseWrapper(localName = "findCarburantResponse", targetNamespace = "http://carburant.ws.fstt.ma/", className = "ma.fstt.ws.carburant.FindCarburantResponse")
    @Action(input = "http://carburant.ws.fstt.ma/CarburantService/findCarburantRequest", output = "http://carburant.ws.fstt.ma/CarburantService/findCarburantResponse")
    public Carburant findCarburant(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<ma.fstt.ws.carburant.Carburant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCarburants", targetNamespace = "http://carburant.ws.fstt.ma/", className = "ma.fstt.ws.carburant.GetCarburants")
    @ResponseWrapper(localName = "getCarburantsResponse", targetNamespace = "http://carburant.ws.fstt.ma/", className = "ma.fstt.ws.carburant.GetCarburantsResponse")
    @Action(input = "http://carburant.ws.fstt.ma/CarburantService/getCarburantsRequest", output = "http://carburant.ws.fstt.ma/CarburantService/getCarburantsResponse")
    public List<Carburant> getCarburants();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "persistCarburant", targetNamespace = "http://carburant.ws.fstt.ma/", className = "ma.fstt.ws.carburant.PersistCarburant")
    @ResponseWrapper(localName = "persistCarburantResponse", targetNamespace = "http://carburant.ws.fstt.ma/", className = "ma.fstt.ws.carburant.PersistCarburantResponse")
    @Action(input = "http://carburant.ws.fstt.ma/CarburantService/persistCarburantRequest", output = "http://carburant.ws.fstt.ma/CarburantService/persistCarburantResponse")
    public void persistCarburant(
        @WebParam(name = "arg0", targetNamespace = "")
        Carburant arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateCarburant", targetNamespace = "http://carburant.ws.fstt.ma/", className = "ma.fstt.ws.carburant.UpdateCarburant")
    @ResponseWrapper(localName = "updateCarburantResponse", targetNamespace = "http://carburant.ws.fstt.ma/", className = "ma.fstt.ws.carburant.UpdateCarburantResponse")
    @Action(input = "http://carburant.ws.fstt.ma/CarburantService/updateCarburantRequest", output = "http://carburant.ws.fstt.ma/CarburantService/updateCarburantResponse")
    public void updateCarburant(
        @WebParam(name = "arg0", targetNamespace = "")
        Carburant arg0);

}
