
package ma.fstt.ws.histocarb;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "HistoCarbService", targetNamespace = "http://histocarb.ws.fstt.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HistoCarbService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteHistoCarb", targetNamespace = "http://histocarb.ws.fstt.ma/", className = "ma.fstt.ws.histocarb.DeleteHistoCarb")
    @ResponseWrapper(localName = "deleteHistoCarbResponse", targetNamespace = "http://histocarb.ws.fstt.ma/", className = "ma.fstt.ws.histocarb.DeleteHistoCarbResponse")
    @Action(input = "http://histocarb.ws.fstt.ma/HistoCarbService/deleteHistoCarbRequest", output = "http://histocarb.ws.fstt.ma/HistoCarbService/deleteHistoCarbResponse")
    public void deleteHistoCarb(
        @WebParam(name = "arg0", targetNamespace = "")
        HistoCarb arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateHistoCarb", targetNamespace = "http://histocarb.ws.fstt.ma/", className = "ma.fstt.ws.histocarb.UpdateHistoCarb")
    @ResponseWrapper(localName = "updateHistoCarbResponse", targetNamespace = "http://histocarb.ws.fstt.ma/", className = "ma.fstt.ws.histocarb.UpdateHistoCarbResponse")
    @Action(input = "http://histocarb.ws.fstt.ma/HistoCarbService/updateHistoCarbRequest", output = "http://histocarb.ws.fstt.ma/HistoCarbService/updateHistoCarbResponse")
    public void updateHistoCarb(
        @WebParam(name = "arg0", targetNamespace = "")
        HistoCarb arg0);

    /**
     * 
     * @return
     *     returns java.util.List<ma.fstt.ws.histocarb.HistoCarb>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHistoCarbs", targetNamespace = "http://histocarb.ws.fstt.ma/", className = "ma.fstt.ws.histocarb.GetHistoCarbs")
    @ResponseWrapper(localName = "getHistoCarbsResponse", targetNamespace = "http://histocarb.ws.fstt.ma/", className = "ma.fstt.ws.histocarb.GetHistoCarbsResponse")
    @Action(input = "http://histocarb.ws.fstt.ma/HistoCarbService/getHistoCarbsRequest", output = "http://histocarb.ws.fstt.ma/HistoCarbService/getHistoCarbsResponse")
    public List<HistoCarb> getHistoCarbs();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "persistHistoCarb", targetNamespace = "http://histocarb.ws.fstt.ma/", className = "ma.fstt.ws.histocarb.PersistHistoCarb")
    @ResponseWrapper(localName = "persistHistoCarbResponse", targetNamespace = "http://histocarb.ws.fstt.ma/", className = "ma.fstt.ws.histocarb.PersistHistoCarbResponse")
    @Action(input = "http://histocarb.ws.fstt.ma/HistoCarbService/persistHistoCarbRequest", output = "http://histocarb.ws.fstt.ma/HistoCarbService/persistHistoCarbResponse")
    public void persistHistoCarb(
        @WebParam(name = "arg0", targetNamespace = "")
        HistoCarb arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ma.fstt.ws.histocarb.HistoCarb
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findHistoCarb", targetNamespace = "http://histocarb.ws.fstt.ma/", className = "ma.fstt.ws.histocarb.FindHistoCarb")
    @ResponseWrapper(localName = "findHistoCarbResponse", targetNamespace = "http://histocarb.ws.fstt.ma/", className = "ma.fstt.ws.histocarb.FindHistoCarbResponse")
    @Action(input = "http://histocarb.ws.fstt.ma/HistoCarbService/findHistoCarbRequest", output = "http://histocarb.ws.fstt.ma/HistoCarbService/findHistoCarbResponse")
    public HistoCarb findHistoCarb(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
