
package ma.fstt.ws.histocarb;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "HistoCarbServiceImplService", targetNamespace = "http://histocarb.ws.fstt.ma/", wsdlLocation = "http://localhost:7777/service/histocarb?wsdl")
public class HistoCarbServiceImplService
    extends Service
{

    private final static URL HISTOCARBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HISTOCARBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName HISTOCARBSERVICEIMPLSERVICE_QNAME = new QName("http://histocarb.ws.fstt.ma/", "HistoCarbServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/service/histocarb?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HISTOCARBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        HISTOCARBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public HistoCarbServiceImplService() {
        super(__getWsdlLocation(), HISTOCARBSERVICEIMPLSERVICE_QNAME);
    }

    public HistoCarbServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HISTOCARBSERVICEIMPLSERVICE_QNAME, features);
    }

    public HistoCarbServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, HISTOCARBSERVICEIMPLSERVICE_QNAME);
    }

    public HistoCarbServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HISTOCARBSERVICEIMPLSERVICE_QNAME, features);
    }

    public HistoCarbServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HistoCarbServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HistoCarbService
     */
    @WebEndpoint(name = "HistoCarbServiceImplPort")
    public HistoCarbService getHistoCarbServiceImplPort() {
        return super.getPort(new QName("http://histocarb.ws.fstt.ma/", "HistoCarbServiceImplPort"), HistoCarbService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HistoCarbService
     */
    @WebEndpoint(name = "HistoCarbServiceImplPort")
    public HistoCarbService getHistoCarbServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://histocarb.ws.fstt.ma/", "HistoCarbServiceImplPort"), HistoCarbService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HISTOCARBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw HISTOCARBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return HISTOCARBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
