
package ma.fstt.ws;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 3.0.2 Generated source
 * version: 3.0
 * 
 */
@WebService(name = "CarburantService", targetNamespace = "http://ws.fstt.ma/")
@XmlSeeAlso({ ObjectFactory.class })
public interface CarburantService {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "deleteCarburant", targetNamespace = "http://ws.fstt.ma/", className = "web.service.carburant.DeleteCarburant")
	@ResponseWrapper(localName = "deleteCarburantResponse", targetNamespace = "http://ws.fstt.ma/", className = "web.service.carburant.DeleteCarburantResponse")
	@Action(input = "http://ws.fstt.ma/CarburantService/deleteCarburantRequest", output = "http://ws.fstt.ma/CarburantService/deleteCarburantResponse")
	public void deleteCarburant(@WebParam(name = "arg0", targetNamespace = "") Carburant arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "persistCarburant", targetNamespace = "http://ws.fstt.ma/", className = "web.service.carburant.PersistCarburant")
	@ResponseWrapper(localName = "persistCarburantResponse", targetNamespace = "http://ws.fstt.ma/", className = "web.service.carburant.PersistCarburantResponse")
	@Action(input = "http://ws.fstt.ma/CarburantService/persistCarburantRequest", output = "http://ws.fstt.ma/CarburantService/persistCarburantResponse")
	public void persistCarburant(@WebParam(name = "arg0", targetNamespace = "") Carburant arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns web.service.carburant.Carburant
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findCarburant", targetNamespace = "http://ws.fstt.ma/", className = "web.service.carburant.FindCarburant")
	@ResponseWrapper(localName = "findCarburantResponse", targetNamespace = "http://ws.fstt.ma/", className = "web.service.carburant.FindCarburantResponse")
	@Action(input = "http://ws.fstt.ma/CarburantService/findCarburantRequest", output = "http://ws.fstt.ma/CarburantService/findCarburantResponse")
	public Carburant findCarburant(@WebParam(name = "arg0", targetNamespace = "") Long arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateCarburant", targetNamespace = "http://ws.fstt.ma/", className = "web.service.carburant.UpdateCarburant")
	@ResponseWrapper(localName = "updateCarburantResponse", targetNamespace = "http://ws.fstt.ma/", className = "web.service.carburant.UpdateCarburantResponse")
	@Action(input = "http://ws.fstt.ma/CarburantService/updateCarburantRequest", output = "http://ws.fstt.ma/CarburantService/updateCarburantResponse")
	public void updateCarburant(@WebParam(name = "arg0", targetNamespace = "") Carburant arg0);

	/**
	 * 
	 * @return returns java.util.List<web.service.carburant.Carburant>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCarburants", targetNamespace = "http://ws.fstt.ma/", className = "web.service.carburant.GetCarburants")
	@ResponseWrapper(localName = "getCarburantsResponse", targetNamespace = "http://ws.fstt.ma/", className = "web.service.carburant.GetCarburantsResponse")
	@Action(input = "http://ws.fstt.ma/CarburantService/getCarburantsRequest", output = "http://ws.fstt.ma/CarburantService/getCarburantsResponse")
	public List<Carburant> getCarburants();

}
